FluentD ingest
sfc-gh-mpilman/foundationdb pull request #17
Opened 2021-04-27 16:27 UTC by sfc-gh-mpilman

2021-04-27 21:09 UTC, sfc-gh-ljoswiak requested changes
I think I understand the design here, but to recap:

* There are different `Ingestor` types, ie `FluentDIngestor` or `NoneIngestor`, which expose a function to handle ingestion of some sample.
* The ingestor implementation handles all sending of serialized samples.
* There is a singleton class `ProfilerConfigT` which holds configuration set through the CLI, and also holds an instance of the ingestion class.
* This configuration interface is also exposed through the special key space, where the user can change the ingestor by committing to the right key.
* The profiler loop itself moves into the `ProfilerImpl` struct which now uses boost signals to change the frequency.

I left a few other comments for small changes.

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on fdbclient/ActorLineageProfiler.cpp
> +			std::for_each(val.begin(), val.end(), [](auto c) { return std::tolower(c); });
```suggestion
			std::for_each(val.begin(), val.end(), std::tolower);
```

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on fdbclient/SpecialKeySpace.actor.cpp
> +		if (didWrite) {
`didWrite` is never set to true.

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on fdbserver/fdbserver.actor.cpp
> +	                 "Set a actor profiler option. Supported options are:\n"
```suggestion
	                 "Set an actor profiler option. Supported options are:\n"
```

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on okteto.yml
> +- 8080:8080
Is this file meant to be included?

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on .stignore
> +.clangd
Is this file meant to be included?

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on fdbclient/ActorLineageProfiler.cpp
> +			std::for_each(val.begin(), val.end(), [](auto c) { return std::tolower(c); });
```suggestion
			std::for_each(val.begin(), val.end(), std::tolower);
```

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on fdbclient/ActorLineageProfiler.h
> +// The FluentD ingestor uses the pimp idiom. This is to make compilation less heavy weight as this implementation has
```suggestion
// The FluentD ingestor uses the pimpl idiom. This is to make compilation less heavy weight as this implementation has
```
😆

2021-04-27 21:09 UTC, sfc-gh-ljoswiak commented on fdbclient/FluentDSampleIngestor.cpp
> +FluentDIngestor::~FluentDIngestor() {}
`delete` `impl` here to prevent memory leak.

2021-04-28 15:05 UTC, sfc-gh-mpilman commented on fdbclient/ActorLineageProfiler.cpp
> +			std::for_each(val.begin(), val.end(), [](auto c) { return std::tolower(c); });
That doesn't work because `std::tolower` (at least on macOS) takes a second default initialized argument for locale.

2021-04-28 15:24 UTC, sfc-gh-mpilman commented on fdbclient/SpecialKeySpace.actor.cpp
> +		if (didWrite) {
good catch, fixed

2021-04-28 15:31 UTC, sfc-gh-mpilman commented on .stignore
> +.clangd
Nope, deleted it

2021-04-28 15:32 UTC, sfc-gh-mpilman commented on fdbclient/ActorLineageProfiler.cpp
> +			std::for_each(val.begin(), val.end(), [](auto c) { return std::tolower(c); });
Same as above, this wouldn't compile.

2021-04-28 21:25 UTC, sfc-gh-ljoswiak approved these changes

2021-04-28 21:25 UTC, merged